[package]
name = "rust_lotto"
version = "1.0.0"
authors = ["Sebastian Michel <contact@devseb.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"